
#' User-defined functions to calculate all steps of the exposure to the credit
#' shock generated by Commerzbank in Q32008 at county level.
#' -----------------------------------------------------------------------------

#' @description
#' Extract data from a specific table of the Amadeus dataset given the firms'
#' category (as defined in Amadeus), a list of variables, and some
#' conditions for the SQL SELECT query. It needs the packages `data.table`,
#' `glue` and `RPostgres`.
#' @param db the database connection object
#' @param table a string with the name of the table in Amadeus
#' @param vars a list of variables' names to subset from the table
#' @param type a character labelling the type of firms (s, m, l, v)
#' @param cond a string with SQL conditions added at the end of the query
#' @return a data.table with the output from the SQL query
get_amadeus <- function(db, table, vars, type, cond = "") {
    aux <- paste(paste0(type, ".", vars), collapse = ", ")
    # assembling SQL query to send through the connector
    query <- glue::glue(
        "SELECT ", aux, " FROM bvd.", table, "_", type,
        " AS ", type, " ", cond
    )
    res <- RPostgres::dbSendQuery(db, query)
    data <- data.table::as.data.table(
        RPostgres::dbFetch(res, n = -1)
    )
    data[, ftype := toupper(type)]
    RPostgres::dbClearResult(res)
    return(data)
} # get_amadeus

#' @param conn the connection object to the database
#' @param tables list of strings containing Amadeus tables' names
#' @param vars list of vectors in the same order specified in the tables
#'  parameter each containing a list of variable names as string
#' @param size a list of flags for the table flags by firm size in the server
#' @param cond a list of conditions to apply to the SQL Select query long as
#' the number of tables to retrieve
#' @return a list with the downloaded tables in the same order specified with
#' the tables parameter
download_firms_data <- function(conn, tables = "amadeus",
                                vars = "*", size = "v", cond = "") {
    # initialize empty list to fill in with as much data.frame as
    # the number of attributes in the tables list
    data <- list()
    for (t in seq_along(tables)) {
        # initialize list for the data acquired from the table t but
        # for all different sizes specified, or only 'very large' by default
        data[[t]] <- list()

        for (s in seq_along(size)) {
            data[[t]][[s]] <- get_amadeus(
                conn, tables[[t]], vars[[t]], size[[s]], cond[[t]]
            )
        } # for size
        data[[t]] <- data.table::rbindlist(data[[t]])
    } # for table

    return(data)
} # download_firms_data